//! cloudflared lifecycle management.
//!
//! Generates and installs a `systemd --user` unit that runs cloudflared
//! against the box's tunnel token, and provides a SIGHUP-based reload
//! primitive for picking up new ingress rules without dropping
//! connections.
//!
//! See `docs/ingress.md`.

use anyhow::{anyhow, bail, Context, Result};
use std::path::{Path, PathBuf};
use tokio::process::Command;

/// systemd unit name for cloudflared. The agent installs this once at
/// `shiku tunnel bootstrap` time; it's then ours to manage.
pub const UNIT_NAME: &str = "cloudflared";

/// systemd unit filename (`<UNIT_NAME>.service`).
fn unit_filename() -> String {
    format!("{UNIT_NAME}.service")
}

/// Path to `~/.config/systemd/user/cloudflared.service`.
fn unit_path() -> Result<PathBuf> {
    let home = std::env::var("HOME").context("HOME not set")?;
    Ok(PathBuf::from(home)
        .join(".config")
        .join("systemd")
        .join("user")
        .join(unit_filename()))
}

/// Generate the systemd unit. Hardening defaults match the rest of
/// Shiku's units (NoNewPrivileges, PrivateTmp, etc).
///
/// `cloudflared_path`: where the operator placed (or symlinked) the
/// cloudflared binary. We don't manage installation in v1 — option (a)
/// from the implementation discussion.
fn render_unit(cloudflared_path: &str, env_file: &str) -> String {
    let mut s = String::new();
    s.push_str("# Generated by shiku — do not edit.\n");
    s.push_str("# Edits will be overwritten on the next bootstrap.\n\n");
    s.push_str("[Unit]\n");
    s.push_str("Description=Cloudflare Tunnel (Shiku-managed)\n");
    s.push_str("After=network-online.target\n");
    s.push_str("Wants=network-online.target\n");
    s.push_str("StartLimitIntervalSec=300\n");
    s.push_str("StartLimitBurst=10\n\n");

    s.push_str("[Service]\n");
    s.push_str("Type=simple\n");
    s.push_str(&format!("EnvironmentFile={env_file}\n"));
    // `--no-autoupdate` keeps the binary version stable — we don't want
    // cloudflared self-updating under us.
    s.push_str(&format!(
        "ExecStart={cloudflared_path} --no-autoupdate tunnel run --token ${{CLOUDFLARED_TUNNEL_TOKEN}}\n"
    ));
    // SIGHUP triggers cloudflared's zero-downtime config reload.
    s.push_str("ExecReload=/bin/kill -HUP $MAINPID\n");
    s.push_str("Restart=always\n");
    s.push_str("RestartSec=10\n\n");

    // Hardening.
    s.push_str("# Hardening (Shiku defaults)\n");
    s.push_str("NoNewPrivileges=yes\n");
    s.push_str("PrivateTmp=yes\n");
    s.push_str("ProtectSystem=strict\n");
    s.push_str("ProtectHome=read-only\n");
    // cloudflared writes a PID file and reads its config from
    // ~/.cloudflared at runtime; allow that one path.
    s.push_str("ReadWritePaths=%h/.cloudflared\n\n");

    s.push_str("StandardOutput=journal\n");
    s.push_str("StandardError=journal\n");
    s.push_str("SyslogIdentifier=cloudflared\n\n");

    s.push_str("[Install]\n");
    s.push_str("WantedBy=default.target\n");

    s
}

/// Resolve `cloudflared` to an absolute path at install time. Returns
/// the path the systemd unit should use directly (so the unit's narrow
/// runtime PATH doesn't matter).
///
/// Search order: the user's PATH (via `command -v`), then conventional
/// per-user locations under `$HOME` that the agent's systemd-user PATH
/// typically excludes. Per-user installs fit Shiku's no-sudo model
/// better than `/usr/local/bin`, so we honor them when present.
fn resolve_cloudflared_binary() -> Result<String> {
    // 1. Whatever the shell's PATH already finds.
    let output = std::process::Command::new("/bin/sh")
        .arg("-c")
        .arg("command -v cloudflared")
        .output()
        .context("running `command -v cloudflared`")?;
    if output.status.success() {
        let path = String::from_utf8(output.stdout)
            .context("cloudflared path was not valid UTF-8")?
            .trim()
            .to_string();
        if !path.is_empty() {
            return Ok(path);
        }
    }

    // 2. Conventional per-user locations.
    if let Ok(home) = std::env::var("HOME") {
        for candidate in &[
            format!("{home}/.local/bin/cloudflared"),
            format!("{home}/bin/cloudflared"),
        ] {
            if std::path::Path::new(candidate).is_file() {
                return Ok(candidate.clone());
            }
        }
    }

    bail!(
        "cloudflared binary not found on PATH or in ~/.local/bin. Install \
         it on the box (e.g. download a static binary from \
         github.com/cloudflare/cloudflared/releases into ~/.local/bin/) \
         and re-run `shiku tunnel bootstrap`."
    )
}

/// Path to the cloudflared env file in tmpfs. Holds
/// `CLOUDFLARED_TUNNEL_TOKEN` (resolved from the `__shiku__` pseudo-app's
/// secrets at activation time). Symmetric with the per-app env file
/// machinery in `activate.rs`.
fn env_file_path() -> Result<PathBuf> {
    let runtime_dir = std::env::var("XDG_RUNTIME_DIR")
        .ok()
        .map(PathBuf::from)
        .or_else(|| {
            let uid = nix::unistd::Uid::current().as_raw();
            Some(PathBuf::from(format!("/run/user/{uid}")))
        })
        .ok_or_else(|| anyhow!("could not resolve XDG_RUNTIME_DIR"))?;
    Ok(runtime_dir.join("shiku").join("__shiku__.env"))
}

/// Write the env file with the resolved tunnel token. Mode 0600.
fn write_env_file(token: &str) -> Result<PathBuf> {
    let path = env_file_path()?;
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating {}", parent.display()))?;
    }
    let body = format!("CLOUDFLARED_TUNNEL_TOKEN={token}\n");
    write_atomic_with_mode(&path, body.as_bytes(), 0o600)?;
    Ok(path)
}

/// Install the cloudflared unit and start it. Idempotent — re-running
/// after a successful install just rewrites the unit file (matching
/// any new fields) and triggers a `daemon-reload`.
///
/// `tunnel_token`: the per-tunnel runtime token from the CF dashboard.
/// Stored in the tmpfs env file at `$XDG_RUNTIME_DIR/shiku/__shiku__.env`.
///
/// `tunnel_id` is needed to seed the initial `~/.cloudflared/config.yml`
/// (so cloudflared has something to load even before any apps are
/// published — it'll just route everything to the catch-all 404).
pub async fn install(tunnel_token: &str, tunnel_id: &str) -> Result<()> {
    let cloudflared_path = resolve_cloudflared_binary()?;

    // Ensure ~/.cloudflared/ exists before referencing it from
    // ReadWritePaths in the systemd unit. Without this directory,
    // systemd rejects the namespace setup with status=226/NAMESPACE
    // and the unit dies in a restart loop.
    let cf_dir = cloudflared_dir()?;
    std::fs::create_dir_all(&cf_dir).with_context(|| format!("creating {}", cf_dir.display()))?;

    // Seed an empty ingress config (just the catch-all 404) so
    // cloudflared has something to load on its first start. Subsequent
    // publishes overwrite this via `ingress::regenerate`.
    let stub_config = format!(
        "# Generated by shiku — do not edit.\n\
         # Edits will be overwritten on the next reconcile.\n\n\
         tunnel: {tunnel_id}\n\
         credentials-file: /dev/null\n\n\
         ingress:\n\
           - service: http_status:404\n"
    );
    let config_path = cf_dir.join("config.yml");
    if !config_path.exists() {
        write_atomic_with_mode(&config_path, stub_config.as_bytes(), 0o600)?;
        tracing::info!(path = %config_path.display(), "seeded initial cloudflared config");
    }

    let env_file = write_env_file(tunnel_token)?;
    let unit_body = render_unit(
        &cloudflared_path,
        env_file
            .to_str()
            .ok_or_else(|| anyhow!("env file path is not UTF-8"))?,
    );

    let unit_path = unit_path()?;
    if let Some(parent) = unit_path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating {}", parent.display()))?;
    }
    write_atomic_with_mode(&unit_path, unit_body.as_bytes(), 0o644)?;
    tracing::info!(unit = %unit_path.display(), "wrote cloudflared unit");

    systemctl(&["daemon-reload"]).await?;
    systemctl(&["enable", &unit_filename()]).await?;
    // Use `restart` rather than `start` so the unit picks up our just-
    // written env file even if it was already running with stale state
    // (e.g. an earlier failed install). For the common case of a fresh
    // box, `restart` on an inactive unit is equivalent to `start`.
    systemctl(&["reset-failed", &unit_filename()]).await?;
    systemctl(&["restart", &unit_filename()]).await?;

    Ok(())
}

/// Path to `~/.cloudflared/`. Pulled out so `install` can create the
/// dir without duplicating the path-construction logic.
fn cloudflared_dir() -> Result<std::path::PathBuf> {
    let home = std::env::var("HOME").context("HOME not set")?;
    Ok(std::path::PathBuf::from(home).join(".cloudflared"))
}

/// Send SIGHUP to the running cloudflared so it picks up new ingress
/// rules without dropping in-flight connections. Equivalent to
/// `systemctl --user reload cloudflared` because the unit's `ExecReload`
/// is `kill -HUP $MAINPID`.
pub async fn reload() -> Result<()> {
    systemctl(&["reload", &unit_filename()]).await?;
    Ok(())
}

/// Stop the cloudflared unit cleanly. Used by `tunnel upgrade` to
/// release the binary before swapping it.
pub async fn stop() -> Result<()> {
    systemctl(&["stop", &unit_filename()]).await?;
    Ok(())
}

/// Restart the cloudflared unit (full bounce, not zero-downtime). Used
/// after binary swaps where SIGHUP isn't sufficient.
pub async fn restart() -> Result<()> {
    // reset-failed in case stop+start raced and tripped the start-limit.
    let _ = systemctl(&["reset-failed", &unit_filename()]).await;
    systemctl(&["restart", &unit_filename()]).await?;
    Ok(())
}

/// Whether the cloudflared unit is currently `active`. Used by status
/// reporting; not part of the publish flow.
pub async fn is_active() -> Result<bool> {
    let output = Command::new("systemctl")
        .args(["--user", "is-active", &unit_filename()])
        .output()
        .await
        .context("running systemctl is-active")?;
    let state = String::from_utf8_lossy(&output.stdout).trim().to_string();
    Ok(state == "active")
}

async fn systemctl(args: &[&str]) -> Result<()> {
    let mut cmd = Command::new("systemctl");
    cmd.arg("--user");
    cmd.args(args);
    let output = cmd
        .output()
        .await
        .with_context(|| format!("running systemctl {args:?}"))?;
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        bail!("systemctl {args:?} failed: {stderr}");
    }
    Ok(())
}

/// Atomic write with explicit mode bits. Mirrors the helper in
/// `activate.rs` — extracting both into a shared util crate is a clean
/// follow-up but not load-bearing right now.
fn write_atomic_with_mode(path: &Path, body: &[u8], mode: u32) -> Result<()> {
    use std::io::Write;
    use std::os::unix::fs::PermissionsExt;
    let parent = path
        .parent()
        .ok_or_else(|| anyhow!("path has no parent: {}", path.display()))?;
    let tmp = parent.join(format!(
        ".{}.tmp.{}",
        path.file_name().and_then(|n| n.to_str()).unwrap_or("file"),
        std::process::id()
    ));
    {
        let mut f = std::fs::File::create(&tmp)
            .with_context(|| format!("creating tempfile {}", tmp.display()))?;
        f.write_all(body)
            .with_context(|| format!("writing tempfile {}", tmp.display()))?;
        f.sync_all().context("fsync tempfile")?;
    }
    std::fs::set_permissions(&tmp, std::fs::Permissions::from_mode(mode))?;
    std::fs::rename(&tmp, path)
        .with_context(|| format!("renaming {} -> {}", tmp.display(), path.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn unit_render_includes_essentials() {
        let unit = render_unit(
            "/usr/local/bin/cloudflared",
            "/run/user/1000/shiku/__shiku__.env",
        );
        assert!(unit.contains("Description=Cloudflare Tunnel"));
        assert!(unit.contains("Type=simple"));
        assert!(unit.contains("ExecStart=/usr/local/bin/cloudflared --no-autoupdate"));
        assert!(unit.contains("--token ${CLOUDFLARED_TUNNEL_TOKEN}"));
        assert!(unit.contains("EnvironmentFile=/run/user/1000/shiku/__shiku__.env"));
        assert!(unit.contains("ExecReload=/bin/kill -HUP $MAINPID"));
        assert!(unit.contains("ProtectHome=read-only"));
        assert!(unit.contains("ReadWritePaths=%h/.cloudflared"));
        assert!(unit.contains("StartLimitIntervalSec=300"));
        // StartLimit* must live in [Unit], not [Service] — systemd warns.
        let unit_section = unit.split("[Service]").next().unwrap();
        assert!(unit_section.contains("StartLimitIntervalSec=300"));
    }

    #[test]
    fn unit_uses_no_autoupdate() {
        let unit = render_unit("/x", "/y");
        // Important: cloudflared shouldn't self-update under us.
        assert!(unit.contains("--no-autoupdate"));
    }
}
