//! Generate `~/.cloudflared/config.yml` from registered apps.
//!
//! Called every time an app's `public` list changes (register, remove,
//! tunnel bootstrap). Walks every registered app's on-disk config and
//! emits an `ingress:` block mapping each declared hostname to that
//! app's allocated localhost port, with a mandatory catch-all 404 last.
//!
//! The whole file is regenerated from scratch each call — there's no
//! "edit in place." That keeps the on-disk content trivially derivable
//! from the apps registry, no persistent ordering state, and any
//! manual edits are intentionally discarded on the next reconcile.
//!
//! See `docs/design/shiku/tunnel.md` §6.4–6.5.

use std::path::{Path, PathBuf};

use anyhow::{anyhow, bail, Context, Result};
use shiku_types::{AppConfig, AppName};

use crate::apps;

const CONFIG_FILE: &str = "config.yml";

/// One ingress rule line. Sorted lexicographically by hostname before
/// emission so the file is deterministic across runs.
#[derive(Debug, Clone, PartialEq, Eq)]
struct Rule {
    hostname: String,
    port: u16,
}

/// Path to `~/.cloudflared/config.yml`.
pub fn config_path() -> Result<PathBuf> {
    let home = std::env::var("HOME").context("HOME not set")?;
    Ok(PathBuf::from(home).join(".cloudflared").join(CONFIG_FILE))
}

/// Regenerate `~/.cloudflared/config.yml` from the apps registry.
///
/// `tunnel_id` comes from `server.toml`. Returns the path that was
/// written, mainly for logging.
pub fn regenerate(tunnel_id: &str) -> Result<PathBuf> {
    let rules = collect_rules()?;
    let body = render(tunnel_id, &rules);
    let path = config_path()?;
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating {}", parent.display()))?;
    }
    write_atomic(&path, body.as_bytes())?;
    tracing::info!(
        path = %path.display(),
        rules = rules.len(),
        "regenerated cloudflared config"
    );
    Ok(path)
}

/// Walk every registered app's config and collect hostname → port rules.
/// Skips apps without an HTTP listen port or an empty public list.
/// Apps that declare hostnames but have no allocated port are an error
/// (they couldn't be reached even if we did emit a rule).
fn collect_rules() -> Result<Vec<Rule>> {
    let names = apps::list().context("listing apps")?;
    let mut rules = Vec::new();
    for name in names {
        // The __shiku__ pseudo-app holds platform secrets; it has no
        // service to expose. Skip it. (See `apps::is_pseudo`.)
        if apps::is_pseudo(&name) {
            continue;
        }
        let cfg = apps::inspect(&name).with_context(|| format!("inspecting `{name}`"))?;
        if cfg.public.is_empty() {
            continue;
        }
        let port = listen_port(&name, &cfg)?;
        for hostname in &cfg.public {
            rules.push(Rule {
                hostname: hostname.clone(),
                port,
            });
        }
    }
    rules.sort_by(|a, b| a.hostname.cmp(&b.hostname));
    Ok(rules)
}

fn listen_port(name: &AppName, cfg: &AppConfig) -> Result<u16> {
    let listen = cfg.listen.as_ref().ok_or_else(|| {
        anyhow!(
            "app `{name}` declares `public` hostnames but has no HTTP \
             listen port. add `shiku::listen_http!()` in code or remove \
             the public list."
        )
    })?;
    if !listen.http {
        bail!(
            "app `{name}` declares `public` hostnames but `listen.http` is \
             false. add `shiku::listen_http!()` in code or remove the \
             public list."
        );
    }
    listen.http_port.ok_or_else(|| {
        anyhow!(
            "app `{name}` wants public hostnames but has no allocated \
             HTTP port; re-run `shiku app register` to allocate one"
        )
    })
}

/// Emit YAML by hand. The shape is small and stable, and avoiding a
/// YAML serde dep keeps the agent's tree honest.
fn render(tunnel_id: &str, rules: &[Rule]) -> String {
    let mut s = String::new();
    s.push_str("# Generated by shiku — do not edit.\n");
    s.push_str("# Edits will be overwritten on the next reconcile.\n\n");
    s.push_str(&format!("tunnel: {tunnel_id}\n"));
    // We use the token form for tunnel auth (set via env);
    // `credentials-file: /dev/null` is the documented placeholder for
    // "I'm using token auth, ignore this."
    s.push_str("credentials-file: /dev/null\n\n");
    s.push_str("ingress:\n");
    for rule in rules {
        s.push_str(&format!("  - hostname: {}\n", yaml_string(&rule.hostname)));
        s.push_str(&format!("    service: http://localhost:{}\n", rule.port));
    }
    // Mandatory catch-all. cloudflared rejects the config without one.
    s.push_str("  - service: http_status:404\n");
    s
}

/// Quote a string for YAML if it contains anything that could trip the
/// parser. Hostnames are very restricted (a-z 0-9 . -) so this is mostly
/// belt-and-braces, but if a future change widens the allowed alphabet
/// we don't want a stray colon to corrupt the file.
fn yaml_string(s: &str) -> String {
    let safe = s
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || c == '.' || c == '-');
    if safe {
        s.to_string()
    } else {
        // Single-quote and double-up any embedded single quotes.
        format!("'{}'", s.replace('\'', "''"))
    }
}

/// Atomic write via tempfile + rename in the same directory.
fn write_atomic(path: &Path, body: &[u8]) -> Result<()> {
    use std::io::Write;
    let parent = path
        .parent()
        .ok_or_else(|| anyhow!("path has no parent: {}", path.display()))?;
    let tmp = parent.join(format!(
        ".{}.tmp.{}",
        path.file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("config"),
        std::process::id()
    ));
    {
        let mut f = std::fs::File::create(&tmp)
            .with_context(|| format!("creating tempfile {}", tmp.display()))?;
        f.write_all(body)
            .with_context(|| format!("writing tempfile {}", tmp.display()))?;
        f.sync_all().context("fsync tempfile")?;
    }
    // 0600 — the file is mode-owner-only because it identifies the
    // tunnel + lists internal services. Not a secret, but no reason to
    // be readable by other users on a shared box either.
    use std::os::unix::fs::PermissionsExt;
    let perms = std::fs::Permissions::from_mode(0o600);
    std::fs::set_permissions(&tmp, perms)?;
    std::fs::rename(&tmp, path)
        .with_context(|| format!("renaming {} -> {}", tmp.display(), path.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_minimal_no_rules() {
        let body = render("abc-123", &[]);
        assert!(body.contains("tunnel: abc-123"));
        assert!(body.contains("credentials-file: /dev/null"));
        assert!(body.contains("ingress:"));
        // Mandatory catch-all always present.
        assert!(body.contains("- service: http_status:404"));
    }

    #[test]
    fn render_with_rules_sorts_alphabetically_in_caller() {
        // The caller (collect_rules) sorts; render itself just emits in
        // the order it receives. Sanity check that the emit order
        // matches input order.
        let rules = vec![
            Rule {
                hostname: "api.augminted.cc".into(),
                port: 49153,
            },
            Rule {
                hostname: "norn.augminted.cc".into(),
                port: 49152,
            },
        ];
        let body = render("uuid", &rules);
        let api_idx = body.find("api.augminted.cc").expect("api line");
        let norn_idx = body.find("norn.augminted.cc").expect("norn line");
        assert!(api_idx < norn_idx, "rules should appear in input order");
        assert!(body.contains("service: http://localhost:49152"));
        assert!(body.contains("service: http://localhost:49153"));
    }

    #[test]
    fn render_catchall_is_last() {
        let rules = vec![Rule {
            hostname: "norn.augminted.cc".into(),
            port: 49152,
        }];
        let body = render("uuid", &rules);
        let rule_idx = body.find("hostname: norn.augminted.cc").unwrap();
        let catchall_idx = body.find("- service: http_status:404").unwrap();
        assert!(catchall_idx > rule_idx, "catch-all must be after rules");
    }

    #[test]
    fn yaml_string_passes_safe_hostnames() {
        assert_eq!(yaml_string("norn.augminted.cc"), "norn.augminted.cc");
        assert_eq!(yaml_string("a-b-c"), "a-b-c");
    }

    #[test]
    fn yaml_string_quotes_unusual_chars() {
        // We never expect this in practice (validation rejects it), but
        // the renderer should be safe regardless.
        let q = yaml_string("a:b");
        assert!(q.starts_with('\'') && q.ends_with('\''));
    }
}
